/**
 * Hype Chat API
 * Hype Chat API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InventoryItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InventoryItem'));
  } else {
    // Browser globals (root is window)
    if (!root.HypeChatApi) {
      root.HypeChatApi = {};
    }
    root.HypeChatApi.AdminsApi = factory(root.HypeChatApi.ApiClient, root.HypeChatApi.InventoryItem);
  }
}(this, function(ApiClient, InventoryItem) {
  'use strict';

  /**
   * Admins service.
   * @module api/AdminsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AdminsApi. 
   * @alias module:api/AdminsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addInventory operation.
     * @callback module:api/AdminsApi~addInventoryCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * adds an inventory item
     * Adds an item to the system
     * @param {Object} opts Optional parameters
     * @param {module:model/InventoryItem} opts.inventoryItem Inventory item to add
     * @param {module:api/AdminsApi~addInventoryCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addInventory = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['inventoryItem'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/inventory', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
