/**
 * Hypechat
 * A simple API to make a resilient chat app for workspaces. Feel free to check our [github repository](https://github.com/taller2fiubafedmanmatsan/AppServer) for more information.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: llauromanuel@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ERRORUNKNOWN'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ERRORUNKNOWN'));
  } else {
    // Browser globals (root is window)
    if (!root.Hypechat) {
      root.Hypechat = {};
    }
    root.Hypechat.HealthcheckApi = factory(root.Hypechat.ApiClient, root.Hypechat.ERRORUNKNOWN);
  }
}(this, function(ApiClient, ERRORUNKNOWN) {
  'use strict';

  /**
   * Healthcheck service.
   * @module api/HealthcheckApi
   * @version 1.0.0
   */

  /**
   * Constructs a new HealthcheckApi. 
   * @alias module:api/HealthcheckApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the rootGet operation.
     * @callback module:api/HealthcheckApi~rootGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ERRORUNKNOWN} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check if server is still working
     * 
     * @param {module:api/HealthcheckApi~rootGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ERRORUNKNOWN}
     */
    this.rootGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = ERRORUNKNOWN;

      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
