/**
 * Hype Chat API
 * Hype Chat API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InventoryItem', 'model/Manufacturer', 'api/AdminsApi', 'api/DevelopersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/InventoryItem'), require('./model/Manufacturer'), require('./api/AdminsApi'), require('./api/DevelopersApi'));
  }
}(function(ApiClient, InventoryItem, Manufacturer, AdminsApi, DevelopersApi) {
  'use strict';

  /**
   * Hype_Chat_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var HypeChatApi = require('index'); // See note below*.
   * var xxxSvc = new HypeChatApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new HypeChatApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new HypeChatApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new HypeChatApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The InventoryItem model constructor.
     * @property {module:model/InventoryItem}
     */
    InventoryItem: InventoryItem,
    /**
     * The Manufacturer model constructor.
     * @property {module:model/Manufacturer}
     */
    Manufacturer: Manufacturer,
    /**
     * The AdminsApi service constructor.
     * @property {module:api/AdminsApi}
     */
    AdminsApi: AdminsApi,
    /**
     * The DevelopersApi service constructor.
     * @property {module:api/DevelopersApi}
     */
    DevelopersApi: DevelopersApi
  };

  return exports;
}));
