/**
 * Hype Chat API
 * Hype Chat API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Manufacturer'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Manufacturer'));
  } else {
    // Browser globals (root is window)
    if (!root.HypeChatApi) {
      root.HypeChatApi = {};
    }
    root.HypeChatApi.InventoryItem = factory(root.HypeChatApi.ApiClient, root.HypeChatApi.Manufacturer);
  }
}(this, function(ApiClient, Manufacturer) {
  'use strict';




  /**
   * The InventoryItem model module.
   * @module model/InventoryItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InventoryItem</code>.
   * @alias module:model/InventoryItem
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param releaseDate {Date} 
   * @param manufacturer {module:model/Manufacturer} 
   */
  var exports = function(id, name, releaseDate, manufacturer) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;
    _this['releaseDate'] = releaseDate;
    _this['manufacturer'] = manufacturer;
  };

  /**
   * Constructs a <code>InventoryItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InventoryItem} obj Optional instance to populate.
   * @return {module:model/InventoryItem} The populated <code>InventoryItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('releaseDate')) {
        obj['releaseDate'] = ApiClient.convertToType(data['releaseDate'], 'Date');
      }
      if (data.hasOwnProperty('manufacturer')) {
        obj['manufacturer'] = Manufacturer.constructFromObject(data['manufacturer']);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Date} releaseDate
   */
  exports.prototype['releaseDate'] = undefined;
  /**
   * @member {module:model/Manufacturer} manufacturer
   */
  exports.prototype['manufacturer'] = undefined;



  return exports;
}));


