/**
 * Hypechat
 * A simple API to make a resilient chat app for workspaces. Feel free to check our [github repository](https://github.com/taller2fiubafedmanmatsan/AppServer) for more information.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: llauromanuel@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Hypechat);
  }
}(this, function(expect, Hypechat) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Hypechat.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('apiUsersMeGet', function() {
      it('should call apiUsersMeGet successfully', function(done) {
        //uncomment below and update the code to test apiUsersMeGet
        //instance.apiUsersMeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUsersMePut', function() {
      it('should call apiUsersMePut successfully', function(done) {
        //uncomment below and update the code to test apiUsersMePut
        //instance.apiUsersMePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUsersPost', function() {
      it('should call apiUsersPost successfully', function(done) {
        //uncomment below and update the code to test apiUsersPost
        //instance.apiUsersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUsersRestorepasswordPost', function() {
      it('should call apiUsersRestorepasswordPost successfully', function(done) {
        //uncomment below and update the code to test apiUsersRestorepasswordPost
        //instance.apiUsersRestorepasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUsersSdadsadsajdPost', function() {
      it('should call apiUsersSdadsadsajdPost successfully', function(done) {
        //uncomment below and update the code to test apiUsersSdadsadsajdPost
        //instance.apiUsersSdadsadsajdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
